baseURL = "https://adamsalves.dev/"

title = "adamsalves"
theme = "hugo-coder"

languageCode = "pt-br"
defaultContentLanguage = "pt-br"
defaultContentLanguageInSubdir = true

paginate = 20

[markup.highlight]
style = "github-dark"
tabWidth = 2

[params]
  author = "Adams Alves"
  description = "Site pessoal e blog de Adams Alves"
  info = "Desenvolvedor Front-End"
  keywords = "blog,desenvolvedor,pessoal,software,front-end,javascript,vue,react"
  avatarurl = "images/avatar.jpg"
  images = ["images/og_cover.png"]

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[params.goatCounter]
  code = "adamsalves"

[params.utterances]
  repo = "adamsalves/adamsalves.dev"
  issueTerm = "pathname"
  theme = "dark"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/adamsalves/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/adams-alves/"

# Menu links
[[menu.main]]
  name = "Sobre"
  weight = 1
  url = "sobre/"